#!/usr/bin/env python3
"""Generate lib/core/app_version.dart from the pubspec version (single source of
truth), so the app can show its version without a plugin.

    tool/fl python3 tool/gen_version.py
"""
import re

src = open("pubspec.yaml", encoding="utf-8").read()
m = re.search(r"^version:\s*([0-9]+\.[0-9]+\.[0-9]+)(?:\+([0-9]+))?", src, re.M)
if not m:
    raise SystemExit("no semantic `version:` found in pubspec.yaml")
version, build = m.group(1), m.group(2) or "0"

with open("lib/core/app_version.dart", "w", encoding="utf-8") as f:
    f.write(
        "// GENERATED by tool/gen_version.py from pubspec.yaml — do not edit.\n"
        f"const String kAppVersion = '{version}';\n"
        f"const int kAppBuild = {build};\n"
    )
print(f"app_version.dart -> {version}+{build}")
