#!/usr/bin/env python3
"""Regenerate lib/features/map/domain/map_catalog.dart from the live
OpenAndroMaps mapsV5 directory listing (real region names + exact sizes).

Run inside the toolchain container (it has network + python3):

    tool/fl python3 tool/gen_map_catalog.py > lib/features/map/domain/map_catalog.dart

Ordering: greater regions first (multi-country / Alps), then countries
alphabetically, then the German Bundesländer. Re-run if the mirror changes.
"""
import re
import sys
import urllib.request

BASE = "https://ftp.gwdg.de/pub/misc/openstreetmap/openandromaps/mapsV5"

# Multi-country / thematic packs in europe/ (everything else there is a country).
REGIONS = {
    "Balkan", "BalticStates", "Pyrenees",
    "Scandinavia-NorthEast", "Scandinavia-SouthWest", "Spain-Portugal",
}


def listing(folder):
    txt = urllib.request.urlopen(f"{BASE}/{folder}/", timeout=60).read().decode(
        "utf-8", "ignore")
    out = []
    for m in re.finditer(
            r'<a href="([^"]+)\.zip">[^<]+</a>\s+[0-9A-Za-z:-]+ [0-9:]+\s+(\d+)',
            txt):
        out.append((m.group(1), int(m.group(2)), folder))
    return out


def pretty(ident):
    s = re.sub(r"(?<=[a-z])(?=[A-Z])", " ", ident)  # split camelCase
    parts = s.split("-")
    if len(parts) == 2 and parts[1] in ("North", "South", "East", "West", "Mid"):
        s = f"{parts[0]} ({parts[1]})"
    else:
        s = s.replace("-", " ")
    return s.replace("Spain Portugal", "Spain & Portugal").replace(
        "Mallorca Ibiza", "Mallorca & Ibiza")


def main():
    europe = listing("europe")
    germany = listing("germany")

    regions, countries = [], []
    for n, s, f in europe:
        if n.startswith("Alps") or n in REGIONS:
            regions.append((n, s, f, "Regions (multi-country)"))
        else:
            countries.append((n, s, f, "Countries"))
    ger_reg = [(n, s, f, "Germany") for n, s, f in germany if n.startswith("Germany")]
    ger_st = [(n, s, f, "Germany") for n, s, f in germany if not n.startswith("Germany")]

    for lst in (regions, countries, ger_reg, ger_st):
        lst.sort(key=lambda x: pretty(x[0]).lower())
    ordered = regions + countries + ger_reg + ger_st

    w = sys.stdout.write
    w("// GENERATED by tool/gen_map_catalog.py from the OpenAndroMaps mapsV5\n")
    w("// listing — do not hand-edit URLs/sizes; regenerate if the mirror changes.\n")
    w("import 'map_region.dart';\n\n")
    w("/// OpenAndroMaps download host (free, no account). Maps are organised by\n")
    w("/// continent / country / region; see https://www.openandromaps.org.\n")
    w(f"const String _oam = '{BASE}';\n\n")
    w("/// Downloadable regions, greater regions first then alphabetical.\n")
    w("const List<MapRegion> kMapCatalog = [\n")
    for n, s, f, g in ordered:
        name = pretty(n).replace("'", "\\'")
        w("  MapRegion(\n")
        w(f"    id: '{n}',\n")
        w(f"    name: '{name}',\n")
        w(f"    group: '{g}',\n")
        w(f"    url: '$_oam/{f}/{n}.zip',\n")
        w(f"    sizeBytes: {s},\n")
        w("  ),\n")
    w("];\n")


if __name__ == "__main__":
    main()
